# Generated by Django 5.2.17 on 2026-10-07 20:09

import django.db.models.deletion
import django.utils.timezone
import inbox.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=inbox.models.thread_token,
                        editable=False,
                        max_length=40,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=80)),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Optional. Only used to tell them you replied.",
                        max_length=254,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "last_message_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "unread",
                    models.BooleanField(
                        default=True,
                        help_text="A visitor message you have not opened yet.",
                    ),
                ),
                (
                    "closed",
                    models.BooleanField(
                        default=False,
                        help_text="Closed threads take no new visitor messages.",
                    ),
                ),
            ],
            options={
                "verbose_name": "conversation",
                "ordering": ["-unread", "-last_message_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_visitor", models.BooleanField(default=True)),
                ("body", models.TextField(max_length=3000)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="inbox.conversation",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
