# Generated by Django 5.2.17 on 2026-09-28 18:24

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                (
                    "short_name",
                    models.CharField(
                        blank=True,
                        help_text="Used where space is tight, for example “Magic”. Optional.",
                        max_length=40,
                    ),
                ),
                ("slug", models.SlugField(max_length=80, unique=True)),
                (
                    "search_aliases",
                    models.CharField(
                        blank=True,
                        help_text="Other words people search for, separated by commas. For example: mtg, magic",
                        max_length=200,
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Lower numbers are listed first."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="show on site"),
                ),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Retailer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("website", models.URLField()),
                (
                    "affiliate_url_template",
                    models.CharField(
                        blank=True,
                        help_text="Leave empty to link straight to the retailer. Otherwise put {url} where the product link goes, for example https://network.example/click?id=123&url={url}. The link is encoded for you.",
                        max_length=500,
                        verbose_name="affiliate link format",
                    ),
                ),
                (
                    "delivery_note",
                    models.CharField(
                        blank=True,
                        help_text="Shown on the how it works page, for example “Free delivery over £50”.",
                        max_length=120,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="show on site"),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("booster_box", "Booster box"),
                            ("elite_trainer_box", "Elite Trainer Box"),
                            ("bundle", "Bundle"),
                            ("collection_box", "Collection box"),
                            ("deck", "Deck"),
                            ("tin", "Tin"),
                            ("booster_pack", "Booster pack"),
                            ("gift_set", "Gift set"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Square or portrait image on a plain background works best. Without one, an outline of the product type is shown.",
                        upload_to="products/",
                    ),
                ),
                (
                    "ean",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, verbose_name="barcode"
                    ),
                ),
                (
                    "release_date",
                    models.DateField(
                        blank=True,
                        help_text="Leave empty to use the set's release date.",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="show on site"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("search_text", models.TextField(blank=True, editable=False)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalogue.game",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=1000, verbose_name="product link")),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "delivery_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Standard delivery for one item to a UK address. 0 for free delivery.",
                        max_digits=6,
                    ),
                ),
                (
                    "delivered_price",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.expressions.CombinedExpression(
                            models.F("price"), "+", models.F("delivery_cost")
                        ),
                        output_field=models.DecimalField(
                            decimal_places=2, max_digits=9
                        ),
                    ),
                ),
                (
                    "availability",
                    models.CharField(
                        choices=[
                            ("in_stock", "In stock"),
                            ("preorder", "Pre-order"),
                            ("out_of_stock", "Out of stock"),
                        ],
                        db_index=True,
                        default="in_stock",
                        max_length=20,
                    ),
                ),
                (
                    "last_checked",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="show on site"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to="catalogue.product",
                    ),
                ),
                (
                    "retailer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to="catalogue.retailer",
                    ),
                ),
            ],
            options={
                "ordering": ["delivered_price"],
                "unique_together": {("product", "retailer")},
            },
        ),
        migrations.CreateModel(
            name="ProductSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=120)),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Set code, for example SV8.5 or OP-10. Optional.",
                        max_length=20,
                    ),
                ),
                ("release_date", models.DateField(blank=True, null=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sets",
                        to="catalogue.game",
                    ),
                ),
            ],
            options={
                "verbose_name": "set",
                "ordering": [
                    "game",
                    models.OrderBy(
                        models.F("release_date"), descending=True, nulls_last=True
                    ),
                    "name",
                ],
                "unique_together": {("game", "slug")},
            },
        ),
        migrations.AddField(
            model_name="product",
            name="product_set",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="catalogue.productset",
                verbose_name="set",
            ),
        ),
        migrations.CreateModel(
            name="OutboundClick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalogue.listing",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outbound_clicks",
                        to="catalogue.product",
                    ),
                ),
                (
                    "retailer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outbound_clicks",
                        to="catalogue.retailer",
                    ),
                ),
            ],
            options={
                "verbose_name": "click to retailer",
                "verbose_name_plural": "clicks to retailers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DailyLowestPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=9)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_prices",
                        to="catalogue.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "daily lowest price",
                "ordering": ["-date"],
                "unique_together": {("product", "date")},
            },
        ),
    ]
