# Generated by Django 5.2.17 on 2026-09-28 19:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="retailer",
            name="delivery_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Charge to deliver one item to a UK address. Used for imported prices.",
                max_digits=6,
                verbose_name="standard delivery",
            ),
        ),
        migrations.AddField(
            model_name="retailer",
            name="free_delivery_over",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Orders of this value or more are delivered free. Leave empty if never.",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="retailer",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("manual", "Entered by hand"),
                    ("shopify", "Shopify store"),
                    ("feed", "Product feed (CSV)"),
                ],
                default="manual",
                max_length=20,
                verbose_name="price source",
            ),
        ),
        migrations.AddField(
            model_name="retailer",
            name="source_url",
            field=models.URLField(
                blank=True,
                help_text="Shopify: the shop address, for example https://shop.example/. Feed: the CSV address. Leave empty for a local file passed to import_prices.",
                max_length=500,
                verbose_name="source address",
            ),
        ),
        migrations.CreateModel(
            name="ImportRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("offers_found", models.PositiveIntegerField(default=0)),
                ("listings_updated", models.PositiveIntegerField(default=0)),
                (
                    "unmatched",
                    models.TextField(
                        blank=True,
                        help_text="Retailer products that no CardScout product has a matching barcode for.",
                    ),
                ),
                ("error", models.TextField(blank=True)),
                (
                    "retailer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_runs",
                        to="catalogue.retailer",
                    ),
                ),
            ],
            options={
                "verbose_name": "price import",
                "ordering": ["-started_at"],
            },
        ),
    ]
