# Generated by Django 5.2.17 on 2026-09-28 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0002_retailer_sources_and_import_runs"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="Filled in by price imports when no image has been uploaded. An uploaded image always takes priority.",
                max_length=1000,
                verbose_name="image from a retailer feed",
            ),
        ),
    ]
