# Generated by Django 5.2.17 on 2026-09-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0003_product_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importrun",
            name="unmatched",
            field=models.TextField(
                blank=True,
                help_text="Shop products that matched nothing. To include one, open our product in admin, add a listing for this retailer and paste the link shown here.",
            ),
        ),
    ]
