# Generated by Django 5.2.17 on 2026-09-29 18:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0004_importrun_help"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("url", models.URLField(max_length=1000)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("image_url", models.URLField(blank=True, max_length=1000)),
                (
                    "confidence",
                    models.PositiveSmallIntegerField(default=0, help_text="0 to 100."),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("review", "Needs a decision"),
                            ("linked", "Linked"),
                            ("ignored", "Not one of ours"),
                        ],
                        db_index=True,
                        default="review",
                        max_length=10,
                    ),
                ),
                ("first_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_seen", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "retailer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_products",
                        to="catalogue.retailer",
                    ),
                ),
                (
                    "suggested",
                    models.ForeignKey(
                        blank=True,
                        help_text="The importer's best guess. Change it if it is wrong, then use the Link action.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="catalogue.product",
                        verbose_name="our product",
                    ),
                ),
            ],
            options={
                "verbose_name": "shop product to review",
                "verbose_name_plural": "shop products to review",
                "ordering": ["-confidence", "title"],
                "unique_together": {("retailer", "url")},
            },
        ),
    ]
