# Generated by Django 5.2.17 on 2026-09-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0005_shop_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retailer",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("manual", "Entered by hand"),
                    ("shopify", "Shopify store"),
                    ("feed", "Product feed (CSV)"),
                    ("website", "Website (sitemap and product pages)"),
                ],
                default="manual",
                max_length=20,
                verbose_name="price source",
            ),
        ),
        migrations.AlterField(
            model_name="retailer",
            name="source_url",
            field=models.URLField(
                blank=True,
                help_text="Shopify: the shop address, for example https://shop.example/. Feed: the CSV address. Website: the shop address; product pages are found through its sitemap and read for schema.org product data. Leave empty for a local file passed to import_prices.",
                max_length=500,
                verbose_name="source address",
            ),
        ),
    ]
