# Generated by Django 5.2.17 on 2026-09-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0006_website_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="back_in_stock_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="When this shop last went from not having it to having it in stock.",
                null=True,
            ),
        ),
    ]
