# Generated by Django 5.2.17 on 2026-10-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0007_listing_back_in_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="retailer",
            name="session_url",
            field=models.URLField(
                blank=True,
                help_text="An address the importer opens before reading product pages, keeping the cookies it sets. For a shop that shows each visitor their own currency, this is its link to switch to pounds, for example https://shop.example/changecurrency/3?returnUrl=%2F.",
                max_length=500,
                verbose_name="visit first",
            ),
        ),
    ]
