# Generated by Django 5.2.17 on 2026-10-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0008_retailer_session_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="amazon_asin",
            field=models.CharField(
                blank=True,
                help_text="Found by the Amazon import. Clear it to make the import look again.",
                max_length=20,
                verbose_name="Amazon product id",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="amazon_checked_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="retailer",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("manual", "Entered by hand"),
                    ("shopify", "Shopify store"),
                    ("feed", "Product feed (CSV)"),
                    ("amazon", "Amazon (Product Advertising API)"),
                    ("website", "Website (sitemap and product pages)"),
                ],
                default="manual",
                max_length=20,
                verbose_name="price source",
            ),
        ),
    ]
