# Generated by Django 5.2.17 on 2026-10-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0009_product_amazon"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="ebay_checked_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="retailer",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("manual", "Entered by hand"),
                    ("shopify", "Shopify store"),
                    ("feed", "Product feed (CSV)"),
                    ("amazon", "Amazon (Product Advertising API)"),
                    ("ebay", "eBay (Browse API)"),
                    ("website", "Website (sitemap and product pages)"),
                ],
                default="manual",
                max_length=20,
                verbose_name="price source",
            ),
        ),
    ]
