# Generated by Django 5.2.17 on 2026-10-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0010_product_ebay"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyPageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("home", "Home"),
                            ("product", "Product"),
                            ("game", "Game"),
                            ("set", "Set"),
                            ("search", "Search"),
                            ("swipe", "Swipe"),
                            ("other", "Other"),
                        ],
                        max_length=12,
                    ),
                ),
                ("key", models.CharField(blank=True, max_length=220)),
                ("hits", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "page views for a day",
                "verbose_name_plural": "page views by day",
                "unique_together": {("date", "kind", "key")},
            },
        ),
        migrations.CreateModel(
            name="DailySearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("query", models.CharField(max_length=100)),
                ("results", models.PositiveIntegerField(default=0)),
                ("hits", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "searches for a day",
                "verbose_name_plural": "searches by day",
                "unique_together": {("date", "query")},
            },
        ),
    ]
