# Generated by Django 5.2.17 on 2026-10-02 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0011_daily_views_and_searches"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=220, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="catalogue.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "old product address",
                "verbose_name_plural": "old product addresses",
            },
        ),
    ]
