# Generated by Django 5.2.17 on 2026-10-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0012_product_alias"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyVisitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("token", models.CharField(max_length=32)),
                ("country", models.CharField(blank=True, max_length=2)),
            ],
            options={
                "verbose_name": "visitor for a day",
                "verbose_name_plural": "visitors by day",
                "unique_together": {("date", "token")},
            },
        ),
    ]
