# Generated by Django 5.2.17 on 2026-10-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0013_daily_visitor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("booster_box", "Booster box"),
                    ("elite_trainer_box", "Elite Trainer Box"),
                    ("bundle", "Bundle"),
                    ("collection_box", "Collection box"),
                    ("deck", "Deck"),
                    ("tin", "Tin"),
                    ("booster_pack", "Booster pack"),
                    ("gift_set", "Gift set"),
                    ("collector_booster_box", "Collector booster box"),
                    ("collector_booster_pack", "Collector booster pack"),
                    ("other", "Other"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
