# Generated by Django 5.2.17 on 2026-10-03 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0014_collector_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyvisitor",
            name="device",
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name="dailyvisitor",
            name="source",
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
