# Generated by Django 5.2.17 on 2026-10-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0015_visitor_device_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyvisitor",
            name="returning",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="dailypageview",
            name="kind",
            field=models.CharField(
                choices=[
                    ("home", "Home"),
                    ("product", "Product"),
                    ("game", "Game"),
                    ("set", "Set"),
                    ("search", "Search"),
                    ("swipe", "Swipe"),
                    ("deals", "Deals"),
                    ("new", "Latest drops"),
                    ("watchlist", "Watchlist"),
                    ("other", "Other"),
                ],
                max_length=12,
            ),
        ),
    ]
