# Generated by Django 5.2.17 on 2026-10-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0018_click_source_and_watched_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailypageview",
            name="kind",
            field=models.CharField(
                choices=[
                    ("home", "Home"),
                    ("product", "Product"),
                    ("game", "Game"),
                    ("set", "Set"),
                    ("search", "Search"),
                    ("swipe", "Swipe"),
                    ("deals", "Deals"),
                    ("new", "Latest drops"),
                    ("watchlist", "Watchlist"),
                    ("watched", "Watchlist rows"),
                    ("install", "Home screen"),
                    ("other", "Other"),
                ],
                max_length=12,
            ),
        ),
    ]
