# Generated by Django 5.2.17 on 2026-10-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0019_install_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="The shop's own name for it, kept so a match can be re-judged when the rules change.",
                max_length=300,
            ),
        ),
    ]
