# Generated by Django 5.2.17 on 2026-10-06 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0020_listing_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="retailer",
            name="collection",
            field=models.SlugField(
                blank=True,
                help_text="Shopify only: read this collection's products instead of the whole shop, for example trading-card-games for a board game shop with one card game section. Products outside it are treated as not stocked.",
                max_length=120,
                verbose_name="Shopify collection",
            ),
        ),
        migrations.AlterField(
            model_name="retailer",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("manual", "Entered by hand"),
                    ("shopify", "Shopify store"),
                    ("feed", "Product feed (CSV or Google Shopping XML)"),
                    ("amazon", "Amazon (Product Advertising API)"),
                    ("ebay", "eBay (Browse API)"),
                    ("website", "Website (sitemap and product pages)"),
                ],
                default="manual",
                max_length=20,
                verbose_name="price source",
            ),
        ),
        migrations.AlterField(
            model_name="retailer",
            name="source_url",
            field=models.URLField(
                blank=True,
                help_text="Shopify: the shop address, for example https://shop.example/. Feed: the CSV or Google Shopping XML address. Website: the shop address; product pages are found through its sitemap and read for schema.org product data. Leave empty for a local file passed to import_prices.",
                max_length=500,
                verbose_name="source address",
            ),
        ),
    ]
