# Generated by Django 5.2.17 on 2026-10-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0021_retailer_collection"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyvisitor",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
