# Generated by Django 5.2.17 on 2026-10-07 06:45

import catalogue.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0022_visitor_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailypageview",
            name="kind",
            field=models.CharField(
                choices=[
                    ("home", "Home"),
                    ("product", "Product"),
                    ("game", "Game"),
                    ("set", "Set"),
                    ("search", "Search"),
                    ("swipe", "Swipe"),
                    ("deals", "Deals"),
                    ("new", "Latest drops"),
                    ("watchlist", "Watchlist"),
                    ("watched", "Watchlist rows"),
                    ("install", "Home screen"),
                    ("alerts", "Stock alerts"),
                    ("other", "Other"),
                ],
                max_length=12,
            ),
        ),
        migrations.CreateModel(
            name="StockAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "token",
                    models.CharField(
                        default=catalogue.models.alert_token, max_length=40, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_alerts",
                        to="catalogue.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "back in stock alert",
                "ordering": ["-created_at"],
                "unique_together": {("product", "email")},
            },
        ),
    ]
