# Generated by Django 5.2.17 on 2026-10-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0023_stock_alerts"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="delivery_known",
            field=models.BooleanField(
                default=True,
                help_text="Untick when the delivery charge is not known. The price then shows as plus delivery, is listed after confirmed delivered prices and never counts as the cheapest.",
            ),
        ),
        migrations.AddField(
            model_name="restock",
            name="delivery_known",
            field=models.BooleanField(
                default=True, help_text="Off when the price is the item price alone."
            ),
        ),
        migrations.AddField(
            model_name="retailer",
            name="delivery_cost_up_to",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="When the standard charge is only known for orders under a value (larger orders cost an unpublished amount), that value. Items above it show as plus delivery. Leave empty otherwise.",
                max_digits=8,
                null=True,
                verbose_name="standard charge only up to",
            ),
        ),
        migrations.AlterField(
            model_name="retailer",
            name="delivery_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=None,
                help_text="Charge to deliver one item to a UK address. Used for imported prices. 0 for free delivery. Leave empty when not known: prices then show as plus delivery and never count as the cheapest delivered.",
                max_digits=6,
                null=True,
                verbose_name="standard delivery",
            ),
        ),
    ]
