# Generated by Django 5.2.17 on 2026-10-09 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0024_delivery_known"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="last_ok_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="sanity",
            field=models.CharField(
                choices=[
                    ("ok", "OK"),
                    ("doubtful", "Doubtful"),
                    ("excluded", "Excluded"),
                ],
                db_index=True,
                default="ok",
                help_text="Excluded prices are kept out of the comparison; doubtful ones are listed under Things to check.",
                max_length=10,
                verbose_name="price verdict",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="sanity_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="verdict changed"
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="sanity_ratio",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="This price divided by what the other shops charge.",
                max_digits=7,
                null=True,
                verbose_name="price against the others",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="sanity_reason",
            field=models.CharField(
                blank=True, max_length=160, verbose_name="verdict reason"
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="trusted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="trusted_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="A price the owner confirmed on Things to check. It counts while it moves less than 10% for 30 days.",
                max_digits=8,
                null=True,
            ),
        ),
    ]
