# Generated by Django 5.2.17 on 2026-10-09 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0025_listing_sanity"),
    ]

    operations = [
        migrations.CreateModel(
            name="TypeBand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("booster_box", "Booster box"),
                            ("elite_trainer_box", "Elite Trainer Box"),
                            ("bundle", "Bundle"),
                            ("collection_box", "Collection box"),
                            ("deck", "Deck"),
                            ("tin", "Tin"),
                            ("booster_pack", "Booster pack"),
                            ("gift_set", "Gift set"),
                            ("collector_booster_box", "Collector booster box"),
                            ("collector_booster_pack", "Collector booster pack"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("n", models.PositiveIntegerField(verbose_name="products")),
                (
                    "p10",
                    models.DecimalField(
                        decimal_places=2, max_digits=9, verbose_name="cheapest tenth"
                    ),
                ),
                ("median", models.DecimalField(decimal_places=2, max_digits=9)),
                (
                    "p90",
                    models.DecimalField(
                        decimal_places=2, max_digits=9, verbose_name="dearest tenth"
                    ),
                ),
                ("computed_at", models.DateTimeField()),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="type_bands",
                        to="catalogue.game",
                    ),
                ),
                (
                    "product_set",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="type_bands",
                        to="catalogue.productset",
                        verbose_name="set",
                    ),
                ),
            ],
            options={
                "verbose_name": "price band",
                "ordering": ["game", "product_type", "product_set"],
                "unique_together": {("game", "product_type", "product_set")},
            },
        ),
    ]
