# Generated by Django 5.2.17 on 2026-10-09 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0026_typeband"),
    ]

    operations = [
        migrations.AddField(
            model_name="retailer",
            name="backoff_until",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="waiting after errors until"
            ),
        ),
        migrations.AddField(
            model_name="retailer",
            name="error_streak",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="failed reads in a row"
            ),
        ),
        migrations.AddField(
            model_name="retailer",
            name="last_error",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="retailer",
            name="last_ok_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last read that worked"
            ),
        ),
        migrations.AddField(
            model_name="retailer",
            name="last_read_seconds",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="last read took (seconds)"
            ),
        ),
        migrations.AddField(
            model_name="retailer",
            name="next_read_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="next read"
            ),
        ),
        migrations.AddField(
            model_name="retailer",
            name="read_every_minutes",
            field=models.PositiveIntegerField(
                default=60,
                help_text="How often to read this shop's prices. A shop that takes a long time to read is read less often: never more than a third of the time.",
                verbose_name="read every (minutes)",
            ),
        ),
        migrations.AddField(
            model_name="retailer",
            name="reading_paused",
            field=models.BooleanField(default=False, verbose_name="reading paused"),
        ),
    ]
