# Generated by Django 5.2.17 on 2026-10-09 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0027_retailer_cadence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retailer",
            name="read_every_minutes",
            field=models.PositiveIntegerField(
                default=60,
                help_text="How often to read this shop's prices. The hourly read rounds it to whole hours: up to 75 minutes is every hour, 76 to 135 every two hours. A shop that takes a long time to read is read less often: never more than a third of the time.",
                verbose_name="read every (minutes)",
            ),
        ),
    ]
