# Generated by Django 5.2.17 on 2026-10-09 03:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0028_retailer_read_every_help"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=1000)),
                ("slug_words", models.CharField(blank=True, max_length=300)),
                (
                    "lastmod",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the shop's sitemap says the page last changed.",
                        null=True,
                    ),
                ),
                ("last_fetched_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_seen_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the page was last in the shop's sitemap.",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="catalogue.product",
                    ),
                ),
                (
                    "retailer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="catalogue.retailer",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["retailer", "last_fetched_at"],
                        name="catalogue_s_retaile_a45598_idx",
                    )
                ],
                "unique_together": {("retailer", "url")},
            },
        ),
    ]
