# Generated by Django 5.2.17 on 2026-10-09 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0029_shoppage"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkerState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "paused",
                    models.BooleanField(
                        default=False,
                        help_text="Pause all: no shop is read or stock checked.",
                    ),
                ),
                ("heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("jobs_done", models.PositiveIntegerField(default=0)),
                ("last_job", models.CharField(blank=True, max_length=120)),
                ("requests_last_hour", models.PositiveIntegerField(default=0)),
                ("errors_last_hour", models.PositiveIntegerField(default=0)),
                ("note", models.CharField(blank=True, max_length=300)),
                ("in_flight", models.JSONField(blank=True, default=list)),
                ("notices", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "background reader",
            },
        ),
    ]
