# Generated by Django 5.2.17 on 2026-10-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0030_workerstate"),
    ]

    operations = [
        migrations.AddField(
            model_name="retailer",
            name="failing_since",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="failing since"
            ),
        ),
    ]
