# Generated by Django 5.2.17 on 2026-10-09 05:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0031_retailer_failing_since"),
    ]

    operations = [
        migrations.AddField(
            model_name="importrun",
            name="note",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="listing",
            name="first_preorder_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="first seen on pre-order"
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="shop_published_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="shop published it"
            ),
        ),
        migrations.AddField(
            model_name="retailer",
            name="collections_ok",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="has a collection list"
            ),
        ),
        migrations.AddField(
            model_name="retailer",
            name="collections_polled_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="collections last looked at"
            ),
        ),
        migrations.CreateModel(
            name="PreorderOpen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Delivered price when pre-orders opened.",
                        max_digits=9,
                    ),
                ),
                (
                    "delivery_known",
                    models.BooleanField(
                        default=True,
                        help_text="Off when the price is the item price alone.",
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preorder_opens",
                        to="catalogue.listing",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preorder_opens",
                        to="catalogue.product",
                    ),
                ),
                (
                    "retailer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preorder_opens",
                        to="catalogue.retailer",
                    ),
                ),
            ],
            options={
                "verbose_name": "pre-order opening",
                "ordering": ["-at"],
            },
        ),
        migrations.CreateModel(
            name="RetailerCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("handle", models.CharField(max_length=200)),
                ("products_count", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("last_read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "retailer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watched_collections",
                        to="catalogue.retailer",
                    ),
                ),
            ],
            options={
                "verbose_name": "watched shop collection",
                "unique_together": {("retailer", "handle")},
            },
        ),
    ]
