# Generated by Django 5.2.17 on 2026-10-09 06:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0032_preorder_pulse"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="finder_checked_at",
            field=models.DateTimeField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="retailer",
            name="suggest_failed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="search last failed"
            ),
        ),
        migrations.AddField(
            model_name="retailer",
            name="suggest_ok",
            field=models.BooleanField(default=True, verbose_name="search answers"),
        ),
        migrations.AddField(
            model_name="shopproduct",
            name="product",
            field=models.ForeignKey(
                blank=True,
                help_text="The product the stockist finder was looking for.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="catalogue.product",
                verbose_name="looked for",
            ),
        ),
        migrations.AddField(
            model_name="shopproduct",
            name="source",
            field=models.CharField(
                choices=[("import", "Price import"), ("finder", "Stockist finder")],
                default="import",
                max_length=10,
                verbose_name="found by",
            ),
        ),
        migrations.CreateModel(
            name="StockistSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "searched_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("linked", "Linked"),
                            ("review", "Waiting for a tap"),
                            ("none", "Not found"),
                            ("ignored", "Owner said no"),
                            ("error", "Could not ask"),
                        ],
                        max_length=10,
                    ),
                ),
                ("url", models.URLField(blank=True, max_length=1000)),
                ("confidence", models.PositiveSmallIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stockist_searches",
                        to="catalogue.product",
                    ),
                ),
                (
                    "retailer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stockist_searches",
                        to="catalogue.retailer",
                    ),
                ),
            ],
            options={
                "verbose_name": "stockist search",
                "unique_together": {("product", "retailer")},
            },
        ),
    ]
