# Generated by Django 5.2.17 on 2026-10-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0033_finder"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopproduct",
            name="availability",
            field=models.CharField(
                blank=True,
                choices=[
                    ("in_stock", "In stock"),
                    ("preorder", "Pre-order"),
                    ("out_of_stock", "Out of stock"),
                ],
                help_text="What the shop said about stock when this row was written. Blank when it was not recorded.",
                max_length=12,
                verbose_name="stock when seen",
            ),
        ),
    ]
