# Generated by Django 5.2.17 on 2026-10-09 07:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0034_shopproduct_availability"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReleaseSourceState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, unique=True)),
                ("last_ok_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, max_length=200)),
                ("signals_found", models.PositiveIntegerField(default=0)),
                ("next_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("pages_day", models.DateField(blank=True, null=True)),
                ("pages_today", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "release source",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="productset",
            name="release_date_source",
            field=models.CharField(
                blank=True,
                help_text="Where the release date came from: a release source, or owner when it was set here. A date set here is never changed by a source.",
                max_length=20,
                verbose_name="date from",
            ),
        ),
        migrations.CreateModel(
            name="Release",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(blank=True, max_length=20)),
                ("release_date", models.DateField(blank=True, null=True)),
                (
                    "precision",
                    models.CharField(
                        choices=[
                            ("day", "Day"),
                            ("month", "Month only"),
                            ("none", "No date"),
                        ],
                        default="none",
                        max_length=5,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        help_text="The release source, or shop:<shop> for a shop's title.",
                        max_length=40,
                    ),
                ),
                ("source_url", models.URLField(blank=True, max_length=500)),
                (
                    "official",
                    models.BooleanField(
                        default=False,
                        help_text="On when the source is the game's publisher.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Waiting for a tap"),
                            ("accepted", "Set added"),
                            ("dismissed", "Not a set"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="The shop's title, for a row from a shop.",
                        max_length=300,
                    ),
                ),
                (
                    "first_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="releases",
                        to="catalogue.game",
                    ),
                ),
                (
                    "product_set",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="releases",
                        to="catalogue.productset",
                        verbose_name="set",
                    ),
                ),
            ],
            options={
                "verbose_name": "announced set",
                "ordering": ["-first_seen_at"],
                "unique_together": {("game", "source", "name")},
            },
        ),
    ]
