# Generated by Django 5.2.17 on 2026-10-09 12:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0035_releases"),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("link", "Linked a shop's page"),
                            ("refuse", "Not this product"),
                            ("hide", "Hid a price"),
                            ("trust", "Counted a doubtful price"),
                            ("merge", "Merged duplicates"),
                            ("apart", "Not the same product"),
                            ("add_set", "Added an announced set"),
                        ],
                        max_length=10,
                    ),
                ),
                ("by_owner", models.BooleanField(default=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("undone_at", models.DateTimeField(blank=True, null=True)),
                ("what", models.CharField(max_length=300)),
                ("why", models.CharField(blank=True, max_length=300)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="catalogue.listing",
                    ),
                ),
                (
                    "other",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="catalogue.product",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="catalogue.product",
                    ),
                ),
                (
                    "product_set",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="catalogue.productset",
                    ),
                ),
                (
                    "release",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="catalogue.release",
                    ),
                ),
                (
                    "shop_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="catalogue.shopproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "check answer",
                "ordering": ["-created_at", "-pk"],
            },
        ),
    ]
