# Generated by Django 5.2.17 on 2026-10-09 13:41

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0036_check_answers"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClaudeJudge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                (
                    "may_act",
                    models.BooleanField(default=False, verbose_name="acts when sure"),
                ),
                ("model", models.CharField(default="claude-opus-5-5", max_length=40)),
                (
                    "effort",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=8,
                    ),
                ),
                (
                    "monthly_budget_usd",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("10.00"), max_digits=6
                    ),
                ),
                (
                    "asked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the owner tapped Ask Claude now.",
                        null=True,
                    ),
                ),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("last_run_note", models.CharField(blank=True, max_length=200)),
                (
                    "problem",
                    models.CharField(
                        blank=True,
                        help_text="key, credit, model, busy or bug.",
                        max_length=10,
                    ),
                ),
                ("problem_at", models.DateTimeField(blank=True, null=True)),
                ("key_hint", models.CharField(blank=True, max_length=4)),
                ("key_saved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Claude judge",
            },
        ),
        migrations.AddField(
            model_name="checkanswer",
            name="undo_note",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="ClaudeAsk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asked_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("found", "Found at another shop"),
                            ("offer", "A shop's price"),
                            ("pair", "Possible duplicates"),
                        ],
                        max_length=6,
                    ),
                ),
                ("row_key", models.CharField(max_length=60)),
                ("fingerprint", models.CharField(max_length=64)),
                ("model_asked", models.CharField(max_length=40)),
                ("model_answered", models.CharField(blank=True, max_length=40)),
                ("effort", models.CharField(max_length=8)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("answered", "Answered"),
                            ("refused", "Declined"),
                            ("cut_off", "Cut off"),
                            ("invalid", "Not understood"),
                            ("error", "Not sent"),
                        ],
                        default="sent",
                        max_length=8,
                    ),
                ),
                ("refusal_category", models.CharField(blank=True, max_length=40)),
                ("verdict", models.CharField(blank=True, max_length=10)),
                ("confidence", models.CharField(blank=True, max_length=6)),
                ("differences", models.JSONField(blank=True, default=list)),
                ("reason", models.CharField(blank=True, max_length=200)),
                ("evidence", models.JSONField(blank=True, default=dict)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("cache_write_tokens", models.PositiveIntegerField(default=0)),
                ("cache_read_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("reserved_micros", models.PositiveBigIntegerField(default=0)),
                (
                    "cost_micros",
                    models.PositiveBigIntegerField(
                        default=0, help_text="US dollars times a million."
                    ),
                ),
                ("request_id", models.CharField(blank=True, max_length=80)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("acted", "Acted"),
                            ("suggested", "Suggested"),
                            ("stale", "Row changed"),
                            ("none", "Nothing"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                (
                    "owner_answer",
                    models.CharField(
                        blank=True,
                        help_text="same, different or hid: what the owner did.",
                        max_length=10,
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="catalogue.listing",
                    ),
                ),
                (
                    "other",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="catalogue.product",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="catalogue.product",
                    ),
                ),
                (
                    "shop_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="catalogue.shopproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Claude answer",
                "ordering": ["-asked_at", "-pk"],
            },
        ),
        migrations.AddField(
            model_name="checkanswer",
            name="ask",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="answer",
                to="catalogue.claudeask",
            ),
        ),
        migrations.AddIndex(
            model_name="claudeask",
            index=models.Index(
                fields=["row_key", "fingerprint"], name="catalogue_c_row_key_b5054d_idx"
            ),
        ),
    ]
