# Generated by Django 5.2.17 on 2026-10-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0037_claude_judge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claudeask",
            name="outcome",
            field=models.CharField(
                choices=[
                    ("sent", "Sent"),
                    ("answered", "Answered"),
                    ("refused", "Declined"),
                    ("cut_off", "Cut off"),
                    ("invalid", "Not understood"),
                    ("rejected", "Refused by Anthropic"),
                    ("error", "Not sent"),
                ],
                default="sent",
                max_length=8,
            ),
        ),
    ]
