# Generated by Django 5.2.17 on 2026-10-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0038_claude_rejected"),
    ]

    operations = [
        migrations.AddField(
            model_name="claudejudge",
            name="key_checked_at",
            field=models.DateTimeField(
                blank=True, help_text="When Anthropic last accepted the key.", null=True
            ),
        ),
        migrations.AddField(
            model_name="claudejudge",
            name="run_asked",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="claudejudge",
            name="run_total",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="claudejudge",
            name="running_since",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="claudejudge",
            name="runs",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
