# Generated by Django 5.2.17 on 2026-10-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0039_claude_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="shop_ean",
            field=models.CharField(
                blank=True,
                help_text="The barcode the shop gives, blank when it gives none. Empty (None) until a read records it, and never recorded for eBay or Amazon, whose barcode is our own.",
                max_length=20,
                null=True,
                verbose_name="shop's barcode",
            ),
        ),
        migrations.AddField(
            model_name="shopproduct",
            name="shop_ean",
            field=models.CharField(
                blank=True,
                help_text="The barcode the shop's page gave, blank when it gave none. Empty (None) when the page was not read.",
                max_length=20,
                null=True,
                verbose_name="shop's barcode",
            ),
        ),
    ]
