# Generated by Django 5.2.18 on 2026-10-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0039_claude_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopproduct",
            name="shop_barcode",
            field=models.CharField(
                blank=True,
                help_text="The barcode the shop's page gave when this row was written. Blank when it gave none, or the row was written before barcodes were kept.",
                max_length=20,
                verbose_name="shop's barcode",
            ),
        ),
    ]
