# Generated by Django 5.2.17 on 2026-10-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0040_shop_barcodes"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkanswer",
            name="title",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="claudeask",
            name="fallback",
            field=models.BooleanField(
                default=False,
                help_text="Part of the answer came from a model other than the one asked.",
            ),
        ),
        migrations.AddField(
            model_name="claudejudge",
            name="acting_since",
            field=models.DateTimeField(
                blank=True,
                help_text="When the owner last tapped Let Claude act.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="checkanswer",
            name="kind",
            field=models.CharField(
                choices=[
                    ("link", "Linked a shop's page"),
                    ("refuse", "Not this product"),
                    ("hide", "Hid a price"),
                    ("trust", "Counted a doubtful price"),
                    ("merge", "Merged duplicates"),
                    ("apart", "Not the same product"),
                    ("add_set", "Added an announced set"),
                    ("checked", "Checked, left as shown"),
                ],
                max_length=10,
            ),
        ),
    ]
