# Generated by Django 5.2.17 on 2026-10-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0041_checked_answers"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="language",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Blank for English.",
                max_length=7,
            ),
        ),
    ]
