# Generated by Django 5.2.17 on 2026-10-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0042_product_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="claudejudge",
            name="sort_all",
            field=models.BooleanField(
                default=False,
                help_text="Claude works through every waiting row, run after run, and also merges duplicates and links shop pages it is sure of. Each act has Undo.",
                verbose_name="sort everything",
            ),
        ),
    ]
