# Generated by Django 5.2.17 on 2026-09-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("label", models.CharField(max_length=120)),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("site", "Header and search box"),
                            ("home", "Home page"),
                            ("browse", "Search results and browsing"),
                            ("product", "Product page"),
                            ("about", "How it works page"),
                            ("footer", "Footer"),
                            ("errors", "Error pages"),
                            ("meta", "Page titles and search engine descriptions"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("heading", "Heading"),
                            ("text", "Short text"),
                            ("paragraphs", "Paragraphs"),
                            ("button", "Button or link label"),
                        ],
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                ("content", models.TextField(blank=True, verbose_name="wording")),
                (
                    "default_content",
                    models.TextField(blank=True, verbose_name="default wording"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="where it appears"),
                ),
                ("placeholders", models.CharField(blank=True, max_length=200)),
                (
                    "is_legal",
                    models.BooleanField(
                        default=False,
                        help_text="Commission and independence statements. Check changes carefully.",
                        verbose_name="legal or disclosure text",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Untick to show the default wording instead. Your edit is kept.",
                        verbose_name="use this wording",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0,
                        editable=False,
                        help_text="Order on the page, from content/registry.py.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "site text",
                "verbose_name_plural": "site text",
                "ordering": ["position", "key"],
            },
        ),
        migrations.CreateModel(
            name="LegalText",
            fields=[],
            options={
                "verbose_name": "legal and disclosure text",
                "verbose_name_plural": "legal and disclosure text",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("content.sitecontent",),
        ),
    ]
