# Generated by Django 5.2.17 on 2026-10-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitecontent",
            name="section",
            field=models.CharField(
                choices=[
                    ("site", "Header and search box"),
                    ("deck", "Swipe page"),
                    ("home", "Home page"),
                    ("deals", "Deals page"),
                    ("feeds", "Feeds (RSS)"),
                    ("alerts", "Back in stock emails"),
                    ("watchlist", "Watchlist page"),
                    ("browse", "Search results and browsing"),
                    ("product", "Product page"),
                    ("about", "How it works page"),
                    ("contact", "Message us page"),
                    ("footer", "Footer"),
                    ("terms", "Terms page"),
                    ("errors", "Error pages"),
                    ("meta", "Page titles and search engine descriptions"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
